
CREATE OR REPLACE PROCEDURE DELETE_PLAYLIST_TRACK(
	playlistId IN PLAYLIST_TRACK.PLAYLIST_ID%TYPE,
	trackId IN PLAYLIST_TRACK.TRACK_ID%TYPE,
	resultMsg OUT VARCHAR2
)
IS
	v_exists NUMBER := 0;
BEGIN
	SELECT COUNT(*) INTO v_exists FROM PLAYLIST_TRACK WHERE PLAYLIST_ID = playlistId;
	IF v_exists = 0 THEN
		resultMsg := '데이터가 없습니다.';
		RETURN;
	END IF;
	DELETE FROM PLAYLIST_TRACK WHERE PLAYLIST_ID  = playlistId AND TRACK_ID = trackId;
	resultMsg := 'SUCCESS';
	COMMIT;
	EXCEPTION
		WHEN OTHERS THEN
			ROLLBACK;
			resultMsg := '오류 발생: ' || SQLERRM;
END;